// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package users

import (
	"database/sql"
)

type User struct {
	ID        int32
	Name      sql.NullString
	Lastname  sql.NullString
	Email     sql.NullString
	Username  sql.NullString
	Password  sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Enabled   sql.NullBool
}
